Repository dnd-side-project/dnd-8th-7-frontend, pull requests merged in 2023-02, with the labels that each got.

#11 feat: 홈 페이지에 사용될 컴포넌트 구현
  .storybook/main.js
  package.json
  public/assets/icons/alarm.svg
  public/assets/images/no_data.png
  public/assets/images/profile_default.png
  src/components/Button/consts.ts
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/types.ts
  src/components/Date/index.stories.tsx
  src/components/Date/index.tsx
  src/components/Header/index.tsx
  src/components/NoData/index.stories.tsx
  src/components/NoData/index.tsx
  src/components/Profile/index.stories.tsx
  src/components/Profile/index.tsx
  src/components/Tabs/index.stories.tsx
  src/components/Tabs/index.tsx
  src/containers/Home/CalendarPanel/index.tsx
  src/containers/Home/DailyBlockPanel/index.tsx
  src/containers/Home/ProfileHeader/index.tsx
  src/containers/Home/index.tsx
  src/styles/globals.css
  src/utils/.gitkeep
  src/utils/formatDate.ts
  src/utils/index.ts
  tailwind.config.js
  yarn.lock
Labels: feature

#17 feat: 홈 페이지의 공통 블록 컴포넌트 구현 및 배치
  public/assets/icons/task_check.svg
  src/components/Block/AddTaskButton/index.tsx
  src/components/Block/Task/index.tsx
  src/components/Block/index.stories.tsx
  src/components/Block/index.tsx
  src/components/DailyBlock/index.stories.tsx
  src/components/DailyBlock/index.tsx
  src/components/Date/index.stories.tsx
  src/components/TaskCheckBox/index.stories.tsx
  src/components/TaskCheckBox/index.tsx
  src/constants/.gitkeep
  src/constants/block.ts
  src/containers/Home/DailyBlockPanel/WeeklyBlocks.tsx
  src/containers/Home/DailyBlockPanel/index.tsx
  src/styles/globals.css
  src/types/block.ts
Labels: feature

#19 feat: 새 블럭 만들기 페이지 추가
  src/components/ColorPicker/index.stories.tsx
  src/components/ColorPicker/index.tsx
  src/containers/NewBlock/index.tsx
  src/pages/blocks/new.tsx
Labels: feature

#21 feat: RN의 새로운 스크린으로 웹뷰 띄우는 브릿지 구현
  src/utils/react-native-webview-bridge/new-webview/index.ts
  src/utils/react-native-webview-bridge/new-webview/rnWebViewBridge.ts
  src/utils/react-native-webview-bridge/types/common.type.ts
  src/utils/react-native-webview-bridge/types/newWebView.type.ts
Labels: feature

#24 feat: Input 컴포넌트에 validation 추가
  package.json
  src/components/BlockInput/index.stories.tsx
  src/components/BlockInput/index.tsx
  src/components/Button/types.ts
  src/components/Input/consts.ts
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/components/Input/types.ts
  src/containers/NewBlock/BlockTitleInput/index.stories.tsx
  src/containers/NewBlock/BlockTitleInput/index.tsx
  src/containers/NewBlock/index.tsx
  src/types/common.type.ts
  tailwind.config.js
Labels: component

#29 feat: CheckBox Component 구현
  public/assets/icons/checkbox_off.svg
  public/assets/icons/checkbox_on.svg
  src/components/CheckBox/index.stories.tsx
  src/components/CheckBox/index.tsx
  src/components/Icons/CheckBoxOffIcon.tsx
  src/components/Icons/CheckBoxOnIcon.tsx
  src/components/Icons/index.ts
Labels: component

#30 feat: 프로필 생성 화면 구현
  package.json
  public/assets/icons/dark_profile.svg
  public/assets/lotties/congratulations.json
  src/components/Button/consts.ts
  src/components/Button/index.tsx
  src/components/Layout/BottomButton.tsx
  src/components/Profile/consts.ts
  src/components/Profile/index.tsx
  src/components/Profile/types.ts
  src/containers/NewBlock/index.tsx
  src/containers/Profile/MyProfile/index.tsx
  src/containers/Profile/New/Congratulation/index.tsx
  src/containers/Profile/New/index.tsx
  src/pages/profiles/index.tsx
  src/pages/profiles/new/done.tsx
  src/pages/profiles/new/index.tsx
  tailwind.config.js
  yarn.lock
Labels: feature

#36 feat: 하루 일기 페이지 레이아웃 구현
  public/assets/icons/smile_face.svg
  src/components/Icons/SmileFaceIcon.tsx
  src/components/Icons/index.ts
  src/components/PercentageProfile/consts.ts
  src/components/PercentageProfile/index.stories.tsx
  src/components/PercentageProfile/index.tsx
  src/components/Profile/index.tsx
  src/containers/DailyDiary/DiaryTextArea/index.tsx
  src/containers/DailyDiary/ProfileHeader/index.tsx
  src/containers/DailyDiary/index.tsx
  src/containers/NewBlock/BlockTitleInput/index.tsx
  src/pages/dailyDiary/index.tsx
Labels: feature, component

#38 feat: msw api mocking 구현
  .env.development
  .env.production
  package.json
  public/mockServiceWorker.js
  src/api/.gitkeep
  src/api/axios.ts
  src/api/index.ts
  src/api/services/DayBlock.interface.ts
  src/api/services/DayBlockAxiosAPI.ts
  src/api/types.ts
  src/components/Block/Task/index.tsx
  src/components/Block/index.stories.tsx
  src/components/Block/index.tsx
  src/constants/block.ts
  src/mocks/browser.ts
  src/mocks/handlers/dayBlocks.ts
  src/mocks/handlers/index.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/mocks/workers.js
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.css
  src/types/block.ts
  yarn.lock
Labels: feature

#39 feat: 블럭 메인 페이지
  src/components/Block/index.stories.tsx
  src/components/Block/index.tsx
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/constants/block.ts
  src/constants/urls.ts
  src/containers/Home/BlockList/DiaryButton.tsx
  src/containers/Home/BlockList/index.tsx
  src/containers/Home/CalendarPanel/index.tsx
  src/containers/Home/DailyBlockPanel/WeeklyBlocks.tsx
  src/containers/Home/DailyBlockPanel/index.tsx
  src/containers/NewBlock/index.tsx
  src/containers/SavedBlock/SavedBlock/index.stories.tsx
  src/containers/SavedBlock/SavedBlock/index.tsx
  src/containers/SavedBlock/index.tsx
  src/store/.gitkeep
  src/store/selectedDate.ts
  src/types/block.ts
Labels: feature

#43 feat: 웹뷰에서 RN으로 실행할 action 정의
  src/components/Layout/Base.tsx
  src/components/Layout/index.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/utils/react-native-webview-bridge/WebBridge.ts
  src/utils/react-native-webview-bridge/new-webview/index.ts
  src/utils/react-native-webview-bridge/new-webview/rnWebViewBridge.ts
  src/utils/react-native-webview-bridge/types/common.type.ts
Labels: feature

#47 feat: 마이 프로필 페이지 구현
  src/components/List/index.stories.tsx
  src/components/List/index.tsx
  src/components/PercentageProfile/index.tsx
  src/components/Switch/index.tsx
  src/constants/path.ts
  src/containers/Profile/EditProfile/index.tsx
  src/containers/Profile/MyProfile/ProfileHeader/index.tsx
  src/containers/Profile/MyProfile/index.tsx
  src/containers/Profile/New/Agreements/index.tsx
  src/containers/Profile/New/Congratulation/index.tsx
  src/containers/Profile/New/index.tsx
  src/containers/Profile/ProfileForm/index.tsx
  src/containers/Profile/Settings/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/settings.tsx
Labels: feature

#49 feat: api 타입 정리 및 Auth API 추가(#44)
  .env.development
  .env.production
  src/api/axios.ts
  src/api/index.ts
  src/api/services/Auth.interface.ts
  src/api/services/AuthAxiosAPI.ts
  src/api/services/DayBlock.interface.ts
  src/api/services/DayBlockAxiosAPI.ts
  src/api/services/types.ts
  src/api/types/auth.types.ts
  src/api/types/base.types.ts
  src/constants/urls.ts
  src/mocks/handlers/dayBlocks.ts
Labels: feature

#50 스타일 변경점 반영
  public/assets/icons/arrow_down.svg
  public/assets/icons/arrow_left.svg
  public/assets/icons/arrow_right.svg
  public/assets/icons/arrow_up.svg
  public/assets/icons/exit.svg
  public/assets/icons/face.svg
  public/assets/icons/friend.svg
  public/assets/icons/lock.svg
  public/assets/icons/more_horiz.svg
  public/assets/icons/more_vert.svg
  public/assets/icons/plus_circle.svg
  public/assets/icons/replay.svg
  public/assets/images/profile_default.png
  src/components/Header/index.tsx
  tailwind.config.js
Labels: feature

#51 feat: 공사 중 페이지 구현
  public/assets/icons/add.svg
  public/assets/icons/exit.svg
  public/assets/icons/plus_circle.svg
  public/assets/icons/preparing.svg
  src/components/Icons/PlusCircleIcon.tsx
  src/components/Icons/index.ts
  src/components/Preparing/index.stories.tsx
  src/components/Preparing/index.tsx
  src/containers/Report/index.tsx
  src/containers/Social/index.tsx
  src/pages/report/index.tsx
  src/pages/social/index.tsx
Labels: feature

#52 feat: 홈의 블록 api mock 연결
  src/components/Block/AddTaskButton/index.tsx
  src/components/Block/Task/index.tsx
  src/components/Block/index.tsx
  src/components/TaskCheckBox/index.stories.tsx
  src/components/TaskCheckBox/index.tsx
  src/containers/Home/BlockList/index.tsx
  src/containers/Home/CalendarPanel/index.tsx
  src/containers/Home/DailyBlockPanel/WeeklyBlocks.tsx
  src/containers/Home/DailyBlockPanel/index.tsx
  src/containers/Home/ProfileHeader/index.tsx
  src/containers/Home/index.tsx
  src/containers/NewBlock/BlockTitleInput/index.tsx
  src/hooks/.gitkeep
  src/hooks/useDebounce.ts
  src/mocks/handlers/dayBlocks.ts
Labels: feature

#54 feat: 사용자 인증 구현
  .env.development
  .env.production
  src/api/axios.ts
  src/api/services/AuthAxiosAPI.ts
  src/constants/path.ts
  src/hoc/withAuth.tsx
  src/pages/_app.tsx
  src/pages/api/login/callback/google.tsx
  src/pages/blocks/new.tsx
  src/pages/blocks/saved.tsx
  src/pages/dailyDiary/index.tsx
  src/pages/home/index.tsx
  src/pages/login/callback/index.tsx
  src/pages/login/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/settings.tsx
  src/pages/profiles/new/agreements.tsx
  src/pages/profiles/new/done.tsx
  src/pages/profiles/new/index.tsx
  src/pages/report/index.tsx
  src/pages/social/index.tsx
  src/pages/webview-test.tsx
Labels: feature
